### ISSUE TITLE
Remove boost dependency

### ISSUE THREAD

**Issue by FireFlyForLife** [AndreyG/ifc-reader#18]
Currently ifc-reader depends on boost-iostreams for memory mapping the ifc file.

I propose letting this be application defined, and which means they can use boost-iostreams themselves, or use something more lightweight like mio, or just reading a file the normal way.

Then the ifc-reader would only need to accept a `const char*`, similar to [raw_pdb](https://github.com/MolecularMatters/raw_pdb/blob/main/src/Examples/ExampleMain.cpp#L113) for example.

We could still have boost-iostreams as a dependency for our examples & unit tests. Just have it not be required for any applications that want to use this as a library.

Let me know what you think!

**Comment by AndreyG** [comment]
It sounds good for me. One minor clarification, that I would prefer `std::span<const std::byte>` instead of raw pointer `const char*`.

**Comment by AndreyG** [comment]
I have moved dependency on boost-iostream from `ifc-core` to `ifc-msvc`, so now it's possible to use `ifc-core` without Boost, see [tests/core](https://github.com/AndreyG/ifc-reader/tree/master/tests/core) for instance.

**Comment by FireFlyForLife** [comment]
This is a good start for sure, and the std::span is indeed a bit safer. But just moving it from `ifc-core` to `ifc-msvc` still means that clients of ifc-core have to have boost installed, otherwise CMake fails to find the dependency and throws an error.

Furthermore it seems to me the ifc environment (be it msvc specific or not) should not dictate how the files should be loaded from disk. I do see how adding that abstraction is difficult though, as it needs to keep track of state. 

What do you think of a similar interface to 
```cpp
class ifc::Environment{
public:
    virtual ~Environment() = default;

    virtual const File& get_file_by_bmi_path(stdfs::path) const;
    virtual const File& get_file_by_module_name(std::string_view) const;
};
```

We define a "Loader" or "DataManager" interface.
```cpp
class ifc::DataLoader {
public:
    virtual ~DataLoader() = default;

    virtual const File& load_from_disk(stdfs::path);
    virtual void unload_file(stdfs::path); // Or possibly by ifc::File&
};
```

Then `ifc::MSVCEnvironment` would take a `DataLoader*`. And the MSVC specific logic could still be abstracted, and kept up to date in the library. But no one is locked into using Boost to load the files. We could have an optional module exposed with that boost file_mapped implementation, which the tests & example would use.

**Comment by AndreyG** [comment]
I have reworked subdivision to libraries and concept of `ifc::Environment`, see [README](https://github.com/AndreyG/ifc-reader/blob/master/README.md). It is pretty close to what you suggested, `ifc-msvc` doesn't depend on `Boost` now. Please, let me know, it it works for you.

**Comment by FireFlyForLife** [comment]
Sorry it has been a bit since I took a look at my project, but now that I got to try it out I like the separation. This issue for me is resolved! Thanks for doing this :)
