### ISSUE TITLE
Make reflifc types classes

### ISSUE THREAD

**Issue by FireFlyForLife** [AndreyG/ifc-reader#21]
Partly a stylistic choice, but it's commonly agreed that structs meant for more "Plain old data" and classes are meant for types with functions.

This is also supported by the [C++ Core Guidelines C.2](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c2-use-class-if-the-class-has-an-invariant-use-struct-if-the-data-members-can-vary-independently).

**Comment by AndreyG** [comment]
While I generally agree with this idea, and it's exactly the reason why for instance `ifc::File` is a class, but `ifc::DyadExpression` is a struct, this criteria of separation between classes and structs is too rough for `reflifc` types. They are [trivially copyable](http://eel.is/c++draft/class.prop#def:class,trivially_copyable) (and after fixing #20 even could be made [trivial](http://eel.is/c++draft/class.prop#def:class,trivial)), and their size is less or equal than `2 * sizeof(void*)`, so they could be passed in register in Itanium ABI. And so they are more structs than classes for me.
