### ISSUE TITLE
Make reflifc types hashable and Comparable.

### ISSUE THREAD

**Issue by FireFlyForLife** [AndreyG/ifc-reader#26]
For my use cases I really need to cache declarations etc to avoid circular dependencies. While traversing all types.

Most of the reflifc types are build as: `ifc::File*` + `ifc::SomeIndex` or `ifc::PartitionData*`.
Those two numbers can easily be hashed together with a hash combine. But I cannot do it outside the library as the members are private.

Would you like me to work on a pull request for this? Or would you prefer to put it in yourself.

**Comment by AndreyG** [comment]
Do you mean something like you have done for `Declaration` in [this commit](https://github.com/AndreyG/ifc-reader/pull/25/commits/3fc78c85d67f65640520ef66d2aff04f39122419)? I'd be glad to get pull request for this.

**Comment by FireFlyForLife** [comment]
Yep exactly! Alright then I will work on adding that to all the types, it will take a bit before the PR is ready though :)

**Comment by FireFlyForLife** [comment]
It took me a bit but I completed making all reflifc types hashable and comparable.
