### ISSUE TITLE
`using enum` is only supported in clang >= 13

### ISSUE THREAD

**Issue by aytey** [AndreyG/ifc-reader#3]
See: https://clang.llvm.org/cxx_status.html

This affects: 

- https://github.com/AndreyG/ifc-reader/blob/b8ea308b01393b7a3d574e5c7c3725178f769e15/examples/dump-decls/Presenter.cpp#L12
- https://github.com/AndreyG/ifc-reader/blob/b8ea308b01393b7a3d574e5c7c3725178f769e15/examples/dump-decls/Presenter.cpp#L50

**Comment by AndreyG** [comment]
Feel free to open PR with corresponding fix, right now in [master](https://github.com/AndreyG/ifc-reader/blob/master/examples/dump-decls/Presenter.cpp) there are already 13 usages of `using enum`.

**Comment by aytey** [comment]
I opened #5 for this
