### ISSUE TITLE
`d.json` suffix doesn't match MSVC

### ISSUE THREAD

**Issue by aytey** [AndreyG/ifc-reader#8]
With `cl.exe` @ `19.30.30705.0`, compiling the following:

```
cl.exe /W4 /WX /experimental:module /interface /sourceDependencies . /std:c++latest /EHsc /MD /c mod_moo.cpp
```

where the argument to [`/sourceDependencies`](https://docs.microsoft.com/en-us/cpp/build/reference/sourcedependencies?view=msvc-160) is `.`, then MSVC gives you:

```
mod_moo.cpp.json
```

There are two things here:

1. `ifc-reader` looks for  the suffix `.d.json`, but the output from MSVC is just `.json`
2. `ifc-reader` looks for `<ifc_name>.<suffix>` but MSVC generates `<src_file_name>.<suffix>` (that is, the name of the output file is the name of the source file and **not** the name of the IFC file)

Maybe a suggested fix here should be that `ifc-reader` could take an additional argument for the path to the source dependencies file?

**Comment by AndreyG** [comment]
This is obsolete now.
